
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (1,'SNAP','approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (2,'SNAP','approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (3,'SNAP','denied','expired');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (4,'SNAP','denied','expired');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (5,'CCAP','approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (6,'CCAP','approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (7,'CCAP','denied','expired');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (8,'CCAP','denied','expired');


insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (9,'Medicaid','approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (10,'Medicaid','approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (11,'Medicaid','denied','expired');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (12,'Medicaid','denied','expired');


insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (13,'Medicare','approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (14,'Medicare','approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (15,'Medicare','denied','expired');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (16,'Medicare','denied','expired');


insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (17,'QHP','approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,BENEFIT_AMT,START_DATE,END_DATE) values (18,'QHP','approved',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (19,'QHP','denied','expired');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,DENIAL_REASN) values (20,'QHP','denied','expired');